name: appimmo
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  file_picker: ^8.1.7
  firebase_app_check: ^0.3.2
  firebase_auth: ^5.4.0
  firebase_database: ^11.3.0
  firebase_messaging: ^15.2.0
  firebase_storage: ^12.4.0
  firebase_ui_auth: ^1.16.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^10.8.5
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  provider: ^6.1.2
  scrollable_reorderable_navbar: ^0.0.2
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
